services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bloglist
    volumes:
      - mongo_data:/data/db
  backend:
    image: backend-bloglist
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/bloglist?authSource=admin
      TEST_MONGODB_URI: mongodb://root:example@mongo:27017/bloglistTest?authSource=admin
      SECRET: NEWSECRET
      PORT: 3000
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    container_name: backend-bloglist
    depends_on:
      - mongo
  frontend:
    image: frontend-bloglist
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    container_name: frontend-bloglist
    depends_on:
      - backend
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist-production
    depends_on:
      - frontend
      - backend
volumes:
  mongo_data:
