POST http://localhost:3001/api/blogs
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR3byIsImlkIjoiNjg5ZDA3MmU0MGM4NWIyMmNlZGQ0NzM2IiwiaWF0IjoxNzU1MTcyNDg1fQ.J_oyOV4clHhnptpYavx62l66aL4fHqcQbuCvk3d_BLU
Content-Type: application/json

  {
    "title": "test4",
    "author": "test4",
    "url": "test2.com",
    "likes": 1099
  }